#!/bin/bash

source ../../conf/sarjitsu.conf

cp conf/sar-index.cfg.example conf/sar-index.cfg

sed -i -r 's#^host\s?=.*#host = '$ES_HOST'#g' conf/sar-index.cfg
sed -i -r 's#^port\s?=.*#port = '$ES_PORT'#g' conf/sar-index.cfg
sed -i -r 's#^protocol\s?=.*#protocol = '$ES_PROTOCOL'#g' conf/sar-index.cfg

sed -i -r 's#^index_prefix\s?=.*#index_prefix = '$INDEX_PREFIX'#g' conf/sar-index.cfg
sed -i -r 's#^index_version\s?=.*#index_version = '$BULK_ACTION_COUNT'#g' conf/sar-index.cfg
sed -i -r 's#^bulk_action_count\s?=.*#bulk_action_count = '$INDEX_VERSION'#g' conf/sar-index.cfg
sed -i -r 's#^number_of_shards\s?=.*#number_of_shards = '$SHARD_COUNT'#g' conf/sar-index.cfg
sed -i -r 's#^number_of_replicas\s?=.*#number_of_replicas = '$REPLICAS_COUNT'#g' conf/sar-index.cfg

sed -i -r 's#^ds_name\s?=.*#ds_name = '$GRAFANA_DS_NAME'#g' conf/sar-index.cfg
sed -i -r 's#^pattern\s?=.*#pattern = '$GRAFANA_DS_PATTERN'#g' conf/sar-index.cfg
sed -i -r 's#^timeField\s?=.*#timeField = '$GRAFANA_TIMEFIELD'#g' conf/sar-index.cfg

sed -i -r 's#^db_host\s?=.*#db_host = '$DB_HOST'#g' conf/sar-index.cfg
sed -i -r 's#^db_name\s?=.*#db_name = '$DB_NAME'#g' conf/sar-index.cfg
sed -i -r 's#^db_user\s?=.*#db_user = '$DB_USER'#g' conf/sar-index.cfg
sed -i -r 's#^db_password\s?=.*#db_password = '$DB_PASSWORD'#g' conf/sar-index.cfg


sed -i -r 's#^api_port\s?=.*#api_port = '$MIDDLEWARE_PORT'#g' conf/sar-index.cfg
sed -i -r 's#^EXPOSE.*#EXPOSE '$MIDDLEWARE_PORT'#g' Dockerfile

echo "building sarjitsu_api"
docker build -t sarjitsu_api . > /dev/null

echo -e "\nRunning $MIDDLEWARE_CONTAINER_ID:"

docker run --name $MIDDLEWARE_CONTAINER_ID \
	-p $MIDDLEWARE_PORT_MAPPING:$MIDDLEWARE_PORT \
	-v /sys/fs/cgroup:/sys/fs/cgroup:ro \
	--privileged -it \
	-d sarjitsu_api
