#!/bin/sh
#/etc/init.d/nodeup

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/src/node_modules

case "$1" in
start)
exec forever --sourceDir=/src server.js
;;
stop)
exec forever stop --sourceDir=/src script.js
;;
*)
echo "Usage: /etc/init.d/nodeup {start|stop}"
exit 1
;;
esac

exit 0