#!/bin/bash

APP_CONF=conf/sarjitsu.conf


log(){
  echo -e "[$(date +'%D %H:%M:%S %Z')] - $*"
}

if [ ! -f $APP_CONF ]; then
    log "$APP_CONF doesn't exist. Taking additional steps to cleanup"
    log "PostgreSQL instance (if it's containerized), might still be running after this"
    CLEAN_IDS=$(docker ps -a | grep -e sarjitsu | awk -F' ' '{print $1}')
else
    source $APP_CONF
    CLEAN_IDS=$(docker ps -a | grep -P '^.*(\ssarjitsu.*|'$METRICSTORE_CONTAINER_ID')$' | awk -F' ' '{print $1}')
fi

if [[ ! -z $CLEAN_IDS ]]; then
    log "cleaning up previously created sarjitsu instances"
    #docker stop $CLEAN_IDS
    docker rm -f $CLEAN_IDS
else
    log "nothing else to cleanup. check output of '$ docker ps -a' manually to verify"
fi
