apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: metricstore
  name: metricstore
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: metricstore
status:
  loadBalancer: {}
