#!/bin/bash

APP_CONF=conf/sarjitsu.conf

source $APP_CONF

log(){
  echo -e "[$(date +'%D %H:%M:%S %Z')] - $*"
}

log "Attempting to start: $METRICSTORE_CONTAINER_ID"
docker start $METRICSTORE_CONTAINER_ID

log "Attempting to start: $DATASOURCE_CONTAINER_ID"
docker start $DATASOURCE_CONTAINER_ID

log "Attempting to start: $FRONTEND_CONTAINER_ID"
docker start $FRONTEND_CONTAINER_ID

log "Attempting to start: $MIDDLEWARE_CONTAINER_ID"
docker start $MIDDLEWARE_CONTAINER_ID

log "Attempting to start: $BACKEND_CONTAINER_ID"
docker start $BACKEND_CONTAINER_ID
