#!/usr/bin/env python3

import os
import configparser

CONFIG_FILE='conf/grafana.ini'
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
SARJITSU_CONF_PATH=os.path.join(BASE_DIR, '../../conf/sarjitsu.conf')

with open(SARJITSU_CONF_PATH, 'r') as f:
    c = f.read().splitlines()
    env_vars = dict([i.split('=') for i in c])

config = configparser.ConfigParser()
config.read(CONFIG_FILE)
config['database']['type'] = env_vars['DB_TYPE']
config['database']['host'] = env_vars['DB_HOST']
config['database']['name'] = env_vars['DB_NAME']
config['database']['user'] = env_vars['DB_USER']
config['database']['password'] = env_vars['DB_PASS']

with open(CONFIG_FILE, 'w') as configfile:
    config.write(configfile)

print("updated grafana config..")

