apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: metricstore
  name: metricstore
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: postgres:9.5
    generation: null
    importPolicy: {}
    name: "9.5"
status:
  dockerImageRepository: ""
