#!/usr/bin/env python3

import time
import sqlite3
import configparser

cfg_name = "/etc/sar-index.cfg"
config = configparser.ConfigParser()
config.read(cfg_name)

GRAFANA_DB_PATH = config.get('Grafana', 'sqlite3_path')
conn = sqlite3.connect(GRAFANA_DB_PATH)
c = conn.cursor()

def tstos(ts=None):
    return time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(ts))

if __name__ == '__main__':
	created = tstos(time.time())
	updated = tstos(time.time())
	ds_name = config.get('Grafana', 'ds_name')
	pattern = config.get('Grafana', 'pattern')
	ds_url = "%s://%s:%s" % (config.get('ElasticSearch', 'protocol'),
			config.get('ElasticSearch', 'host'),
			config.get('ElasticSearch', 'port'))

	interval = '{"interval":"Daily","timeField":"%s"}' % \
					(config.get('Grafana', 'timeField'))

	values = "(1,1,0,'elasticsearch','%s','proxy','%s','','','%s',0,'','',0,'%s', '%s', '%s')" \
				% (ds_name, ds_url, pattern, interval, created, updated)

	c.execute("INSERT INTO data_source VALUES %s" % (values))
	conn.commit()
	conn.close()
