#!/bin/bash

user_interrupt(){
    echo -e "\n\nKeyboard Interrupt detected."
    echo -e "Stopping Task Manager..."
    exit
}

trap user_interrupt SIGINT
trap user_interrupt SIGTSTP

start_daemon() {
    echo "starting daemon.."
    ES_HOST=$(egrep '^(host)\s?=.*$' /etc/sar-index.cfg  | awk -F'=' '{print $NF}' | tr -d '[[:space:]]')
    ES_PORT=$(egrep '^(port)\s?=.*$' /etc/sar-index.cfg  | awk -F'=' '{print $NF}' | tr -d '[[:space:]]')
    ES_PROTOCOL=$(egrep '^(protocol)\s?=.*$' /etc/sar-index.cfg  | awk -F'=' '{print $NF}' | tr -d '[[:space:]]')
    while :; do
    	status=`curl -s $ES_PROTOCOL://$ES_HOST:$ES_PORT/_cluster/health | egrep "yellow|green"`
    	if [[ ! -z $status ]]; then
    	    /scripts/es-create-sarjitsu-templates
    	    if [ $? -eq 0 ]; then
    	    	echo "created templates.."
    	    else
        		echo "index template creation for sarjitsu failed."
            exit -1
    	    fi

          systemctl stop grafana-server
          /scripts/update_grafana_config
          sleep 2
          wait
          # sed -i -r 's#;type\s?=.*#type='$DB_TYPE'#g' /etc/grafana/grafana.ini
          # sed -i -r 's#;host\s?=.*#host='$DB_HOST'#g' /etc/grafana/grafana.ini
          # sed -i -r 's#;name\s?=.*#name='$DB_NAME'#g' /etc/grafana/grafana.ini
          # sed -i -r 's#;user\s?=.*#user='$DB_USER'#g' /etc/grafana/grafana.ini
          # sed -i -r 's#;password\s?=.*#password='$DB_PASSWORD'#g' /etc/grafana/grafana.ini
          systemctl start grafana-server
          systemctl restart api_engine
    	    /scripts/create_datasource
    	    if [ $? -eq 0 ]; then
    	    	echo "created datasource.."
    	    else
        		echo "index template creation for sarjitsu failed."
            exit -1
    	    fi

    	    break
    	else
    	    echo "unable to contact Elasticsearch; sleeping for 2 secs"
    	    sleep 2
    	fi
    done
}

start_daemon
