#!/bin/bash

user_interrupt(){
    echo -e "\n\nKeyboard Interrupt detected."
    echo -e "Stopping Task Manager..."
    exit
}

trap user_interrupt SIGINT
trap user_interrupt SIGTSTP

start_daemon() {
    echo "starting daemon.."
    ES_HOST=$(egrep '^(host)\s?=.*$' /etc/sar-index.cfg  | awk -F' ' '{print $3}')
    ES_PORT=$(egrep '^(port)\s?=.*$' /etc/sar-index.cfg  | awk -F' ' '{print $3}')
    ES_PROTOCOL=$(egrep '^(protocol)\s?=.*$' /etc/sar-index.cfg  | awk -F' ' '{print $3}')
    while :; do
	
	status=`curl -s $ES_PROTOCOL://$ES_HOST:$ES_PORT/_cluster/health | egrep "yellow|green"`
	if [[ ! -z $status ]]; then
	    /scripts/es-create-sarjitsu-templates
	    if [ $? -eq 0 ]; then
	    	echo "created templates.."
	    else
		echo "index template creation for sarjitsu failed."
	    fi

	    /scripts/create_datasource	    
	    if [ $? -eq 0 ]; then
	    	echo "created datasource.."
	    else
		echo "index template creation for sarjitsu failed."
	    fi

	    break
	else
	    echo "unable to contact Elasticsearch; sleeping for 2 secs"
	    sleep 2
	fi
    done
}

start_daemon
