#!/usr/bin/env python3

import os
import configparser

CONFIG_FILE='/etc/grafana/grafana.ini'

config = configparser.ConfigParser()
config.read(CONFIG_FILE)
config['database']['type'] = os.environ.get('DB_TYPE')
config['database']['host'] = os.environ.get('DB_HOST')
config['database']['name'] = os.environ.get('DB_NAME')
config['database']['user'] = os.environ.get('DB_USER')
config['database']['password'] = os.environ.get('DB_PASSWORD')

with open(CONFIG_FILE, 'w') as configfile:
    config.write(configfile)
