#!/usr/bin/env python3

import os
import configparser

CONFIG_FILE='/etc/grafana/grafana.ini'

with open('/etc/sarjitsu/db_environment', 'r') as f:
    c = f.read().splitlines()
    env_vars = dict([i.split('=') for i in c])

config = configparser.ConfigParser()
config.read(CONFIG_FILE)
config['database']['type'] = env_vars['DB_TYPE']
config['database']['host'] = env_vars['DB_HOST']
config['database']['name'] = env_vars['DB_NAME']
config['database']['user'] = env_vars['DB_USER']
config['database']['password'] = env_vars['DB_PASS']

with open(CONFIG_FILE, 'w') as configfile:
    config.write(configfile)

print("updated grafana config..")
