#!/bin/bash

log(){
  echo -e "[$(date +'%D %H:%M:%S %Z')] - $*"
}

APP_CONF=$1
if [[ -z $APP_CONF ]]; then
	APP_CONF=../../conf/sarjitsu.conf
fi

if [ ! -f $APP_CONF ]; then
	log "sarjitsu.conf: file does not exist. Supply it's path as 1st argument"
	exit -1
fi

source $APP_CONF

cp conf/grafana.ini.example conf/grafana.ini
./update_grafana_config

# sed -i -r 's#dport 80#dport '$GRAFANA_PORT'#g' Dockerfile
sed -i -r 's#^EXPOSE.*#EXPOSE '$GRAFANA_PORT'#g' Dockerfile

log "building sarjitsu_grafana"
docker build -t sarjitsu_grafana . > /dev/null

log "Running $FRONTEND_CONTAINER_ID:"

docker run  --name $FRONTEND_CONTAINER_ID \
	-p $FRONTEND_PORT_MAPPING:$GRAFANA_PORT \
	-v /sys/fs/cgroup:/sys/fs/cgroup:ro \
	--privileged -it \
	-d sarjitsu_grafana
