#!/bin/bash

source ../../conf/sarjitsu.conf

cp conf/grafana.ini.example conf/grafana.ini
./update_grafana_config

# sed -i -r 's#dport 80#dport '$GRAFANA_PORT'#g' Dockerfile
sed -i -r 's#^EXPOSE.*#EXPOSE '$GRAFANA_PORT'#g' Dockerfile

echo "building sarjitsu_grafana"
docker build -t sarjitsu_grafana . > /dev/null

echo -e "\nRunning $FRONTEND_CONTAINER_ID:"

docker run  --name $FRONTEND_CONTAINER_ID \
	-p $FRONTEND_PORT_MAPPING:$GRAFANA_PORT \
	-v /sys/fs/cgroup:/sys/fs/cgroup:ro \
	--privileged -it \
	-d sarjitsu_grafana
