#!/usr/bin/env python3

# updates grafana.ini with db credentials
# from sarjitsu.conf file (for postgres)

import os
import configparser

CONFIG_FILE='conf/grafana.ini'
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
SARJITSU_CONF_PATH=os.path.join(BASE_DIR, '../../conf/sarjitsu.conf')

with open(SARJITSU_CONF_PATH, 'r') as f:
    c = f.read().splitlines()
    # cleanup bash for comments / newlines
    c = [i for i in c if not i.startswith('#')]
    while '' in c:
        c.remove('')
    env_vars = dict([i.split('=') for i in c])

config = configparser.ConfigParser()
config.read(CONFIG_FILE)

config['database']['type'] = env_vars['GRAFANA_DB_TYPE']
config['database']['host'] = "%s:%s" % (env_vars['DB_HOST'],
                                        env_vars['DB_PORT'])
config['database']['name'] = env_vars['DB_NAME']
config['database']['user'] = env_vars['DB_USER']
config['database']['password'] = env_vars['DB_PASSWORD']

with open(CONFIG_FILE, 'w') as configfile:
    config.write(configfile)

print("updated grafana config..")
