#!/bin/bash

log(){
  echo -e "[$(date +'%D %H:%M:%S %Z')] - $*"
}

APP_CONF=$1
if [[ -z $APP_CONF ]]; then
	APP_CONF=../../.env
fi

if [ ! -f $APP_CONF ]; then
	log ".env file does not exist. Supply it's path as 1st argument"
	exit -1
fi

source $APP_CONF

log "Pulling and Running $METRICSTORE_CONTAINER_ID:"
docker run --name $METRICSTORE_CONTAINER_ID \
	-e POSTGRES_PASSWORD=$DB_PASSWORD \
	-e POSTGRES_USER=$DB_USER \
	-e POSTGRES_DB=$DB_NAME \
	-d postgres:9.5
