#!/bin/bash

source ../../conf/sarjitsu.conf

echo "building sarjitsu_elasticsearch"
sed -i -r 's#elasticsearch\$RANDOM#'$ES_CLUSTER_NAME'#g' Dockerfile
docker build -t sarjitsu_elasticsearch . > /dev/null

echo -e "\nRunning $DATASOURCE_CONTAINER_ID:"

docker run --name $DATASOURCE_CONTAINER_ID \
	-p $DATASOURCE_PORT_MAPPING:9200 \
	-v /sys/fs/cgroup:/sys/fs/cgroup:ro \
	--privileged -it \
	-d sarjitsu_elasticsearch
