#!/usr/bin/env python3

import time
import configparser
# import sqlite3
import psycopg2

config = configparser.ConfigParser()

def tstos(ts=None):
    return time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(ts))


if __name__ == '__main__':
    cfg_name = "/etc/sar-index.cfg"
    config.read(cfg_name)

    db_host = config.get('Postgres','db_host')
    db_port = config.get('Postgres','db_port')
    db_name = config.get('Postgres','db_name')
    db_user = config.get('Postgres','db_user')
    db_pass = config.get('Postgres','db_password')

    conn = psycopg2.connect("dbname='%s' user='%s' host='%s' port='%s' password='%s'" %
                            (db_name, db_user, db_host, db_port, db_pass))
    c = conn.cursor()

    created = tstos(time.time())
    updated = tstos(time.time())


    ds_name = config.get('Grafana', 'ds_name')
    pattern = config.get('Grafana', 'pattern')
    ds_url = "%s://%s:%s" % (config.get('ElasticSearch', 'protocol'),
			     config.get('ElasticSearch', 'host'),
			     config.get('ElasticSearch', 'port'))

    interval = '{"interval":"Daily","timeField":"%s"}' % \
	       (config.get('Grafana', 'timeField'))

    values = "(1,1,0,'elasticsearch','%s','proxy','%s','','','%s',False,'','',False,'%s', '%s', '%s')" \
	     % (ds_name, ds_url, pattern, interval, created, updated)

    c.execute("INSERT INTO data_source VALUES %s" % (values))
    conn.commit()
    conn.close()
