#!/bin/bash

log(){
  echo -e "[$(date +'%D %H:%M:%S %Z')] - $*"
}

user_interrupt(){
    log "\n\nKeyboard Interrupt detected."
    log "Stopping Task Manager..."
    exit
}

trap user_interrupt SIGINT
trap user_interrupt SIGTSTP

start_daemon() {
    log "starting daemon.."
    ES_HOST=$(egrep '^(host)\s?=.*$' /etc/sar-index.cfg  | awk -F'=' '{print $NF}' | tr -d '[[:space:]]')
    ES_PORT=$(egrep '^(port)\s?=.*$' /etc/sar-index.cfg  | awk -F'=' '{print $NF}' | tr -d '[[:space:]]')
    ES_PROTOCOL=$(egrep '^(protocol)\s?=.*$' /etc/sar-index.cfg  | awk -F'=' '{print $NF}' | tr -d '[[:space:]]')
    while :; do
    	status=`curl -s $ES_PROTOCOL://$ES_HOST:$ES_PORT/_cluster/health | egrep "yellow|green"`
    	if [[ ! -z $status ]]; then
          /scripts/create_datasource
          if [ $? -eq 0 ]; then
            log "Created datasource for Grafana."
            sleep 1
          else
            log "Grafana's datasource creation failed!"
            exit -1
          fi

          log "Attempting to create Index template in Elasticsearch"
          log "This might take 5-10 multiple attempts.."
          /scripts/es-create-sarjitsu-templates
          if [ ! $? -eq 0 ]; then
            log "ES index template creation for sarjitsu failed!"
            exit -1
          else
            log "ES index template created."
          fi

    	    break
    	else
    	    echo "$(date +'%D %H:%M:%S %Z') - unable to contact Elasticsearch; sleeping for 2 secs"
    	    sleep 2
    	fi
    done
}

start_daemon
